Traceback (most recent call last):
  File "/scratch/bbc33/ece509-final/dist_lasso/hello.py", line 68, in <module>
    main()
  File "/scratch/bbc33/ece509-final/dist_lasso/hello.py", line 60, in main
    error = global_mean - validation_mean
ValueError: operands could not be broadcast together with shapes (8,) (1600,) 
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[51340,1],0]
  Exit code:    1
--------------------------------------------------------------------------
